### ISSUE TITLE
Http Request takes too long

### ISSUE THREAD

**Issue by ThraaxSession** [sdeleuze/kotlin-script-templating#5]
Hi,

it's a nice demo app. :)

I saw it takes really long for each HTT request. This is the corresponding log on the console:

```
warning: some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
warning: library has Kotlin runtime bundled into it
``` 

Regards
Gino

**Comment by sdeleuze** [comment]
Yeah it needs to supports caching via JSR 223 `CompiledScript` + some cache.

**Comment by sdeleuze** [comment]
I have created a WIP branch (it does not work yet, error on Kotlin Script engine side): https://github.com/sdeleuze/kotlin-script-templating/tree/caching

**Comment by sdeleuze** [comment]
Solved by https://github.com/sdeleuze/kotlin-script-templating/commit/41a59786f31be54ecd3b510e496237e07b7b0108
